namespace ProductivityTracker;

internal static class Loc
{
    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
    {
        ["en"] = new()
        {
            ["dashboard"] = "Dashboard",
            ["processes"] = "Processes",
            ["web"] = "Web",
            ["screenshots"] = "Screenshots",
            ["reports"] = "Reports",
            ["settings"] = "Settings",
            ["status"] = "Status",
            ["open_process_history"] = "Open process history with user, start time, end time, duration, process name and window title.",
            ["open_web_history"] = "Open web history.",
            ["open_screenshots"] = "Open screenshots.",
            ["plugin_status"] = "Plugin status",
            ["retention_days"] = "Retention",
            ["user"] = "User",
            ["data_folder"] = "Data folder",
            ["database"] = "Database",
            ["screenshot_folder"] = "Screenshot folder",
            ["screenshot_interval_min"] = "Screenshot interval minutes",
            ["screenshot_retention_days"] = "Screenshot retention days",
            ["idle_threshold_min"] = "Idle threshold minutes",
            ["activity_retention_days"] = "Activity retention days",
            ["plugin_heartbeat_sec"] = "Plugin heartbeat seconds",
            ["quiet_operation"] = "Quiet operation",
            ["notifications"] = "Show notifications",
            ["language"] = "Language",
            ["autostart"] = "Start with Windows",
            ["database_path"] = "Database path",
            ["save_settings"] = "Save settings",
            ["change_password"] = "Change password",
            ["open_data_folder"] = "Open data folder",
            ["run_cleanup_now"] = "Run cleanup now",
            ["settings_saved"] = "Settings saved.",
            ["password_changed"] = "Password changed.",
            ["current_password_invalid"] = "Current password is invalid.",
            ["report_date"] = "Report date",
            ["generate_report"] = "Generate and open report",
            ["open_reports_folder"] = "Open reports folder",
            ["from"] = "From",
            ["to"] = "To",
            ["search"] = "Search...",
            ["refresh"] = "Refresh",
            ["all"] = "all",
            ["plugin"] = "plugin",
            ["fallback_window_title"] = "fallback_window_title",
            ["limited_mode"] = "limited mode, plugin not detected yet",
            ["active_last_event"] = "active, last event {0} seconds ago",
            ["limited_last_event"] = "limited mode, last event {0}",
            ["no_activity"] = "No process activity recorded yet.",
            ["was_opened_at"] = "{0} was opened at {1}, last closed at {2}, total {3}.",
            ["cleanup_completed"] = "Cleanup completed.",
            ["db_unavailable"] = "Database unavailable. Application cannot start.",
            ["db_error_title"] = "Database Error",
            ["browse"] = "Browse",
            ["current_password"] = "Current password",
            ["new_password"] = "New password",
            ["confirm_password"] = "Confirm password",
            ["save"] = "Save",
            ["cancel"] = "Cancel",
            ["exit"] = "Exit",
            ["password_min_length"] = "Password must contain at least 5 characters.",
            ["passwords_do_not_match"] = "Passwords do not match.",
            ["create_password"] = "Create local access password",
            ["password_note"] = "This password is required to open the app UI and close the tray app.",
            ["password_label"] = "Password",
            ["confirm_password_label"] = "Confirm password",
            ["open_application"] = "Open application",
            ["close_app"] = "Close 1984",
            ["invalid_password"] = "Invalid password.",
            ["enter_password"] = "Enter password",
            ["col_user"] = "User",
            ["col_process_name"] = "Process",
            ["col_window_title"] = "Title",
            ["col_started_at"] = "Start",
            ["col_duration"] = "Duration",
            ["col_daily_total"] = "Daily total",
            ["col_browser"] = "Browser",
            ["col_domain"] = "Domain",
            ["col_url"] = "URL",
            ["col_captured_at"] = "Screenshot time",
            ["install_plugin"] = "Install browser plugin",
            ["plugin_install_instructions"] = "Chrome/Edge/Brave/Opera: open extensions page, enable Developer mode, Load unpacked → select 'chromium' folder.\nFirefox: about:debugging → Load Temporary Add-on → select 'firefox/manifest.json'.",
            ["report_auto_interval"] = "Auto-report interval (min, 0=off)",
        },
        ["ru"] = new()
        {
            ["dashboard"] = "Панель",
            ["processes"] = "Процессы",
            ["web"] = "Интернет",
            ["screenshots"] = "Скриншоты",
            ["reports"] = "Отчёты",
            ["settings"] = "Настройки",
            ["status"] = "Статус",
            ["open_process_history"] = "История процессов: пользователь, начало, конец, длительность, процесс, заголовок окна.",
            ["open_web_history"] = "История браузера.",
            ["open_screenshots"] = "Скриншоты.",
            ["plugin_status"] = "Статус плагина",
            ["retention_days"] = "Хранение",
            ["user"] = "Пользователь",
            ["data_folder"] = "Папка данных",
            ["database"] = "База данных",
            ["screenshot_folder"] = "Папка скриншотов",
            ["screenshot_interval_min"] = "Интервал скриншотов (мин)",
            ["screenshot_retention_days"] = "Хранение скриншотов (дней)",
            ["idle_threshold_min"] = "Порог бездействия (мин)",
            ["activity_retention_days"] = "Хранение активности (дней)",
            ["plugin_heartbeat_sec"] = "Пульс плагина (сек)",
            ["quiet_operation"] = "Тихий режим",
            ["notifications"] = "Уведомления",
            ["language"] = "Язык",
            ["autostart"] = "Запуск с Windows",
            ["database_path"] = "Путь к базе данных",
            ["save_settings"] = "Сохранить настройки",
            ["change_password"] = "Сменить пароль",
            ["open_data_folder"] = "Открыть папку данных",
            ["run_cleanup_now"] = "Очистка сейчас",
            ["settings_saved"] = "Настройки сохранены.",
            ["password_changed"] = "Пароль изменён.",
            ["current_password_invalid"] = "Неверный текущий пароль.",
            ["report_date"] = "Дата отчёта",
            ["generate_report"] = "Создать и открыть отчёт",
            ["open_reports_folder"] = "Открыть папку отчётов",
            ["from"] = "С",
            ["to"] = "По",
            ["search"] = "Поиск...",
            ["refresh"] = "Обновить",
            ["all"] = "все",
            ["plugin"] = "плагин",
            ["fallback_window_title"] = "заголовок_окна",
            ["limited_mode"] = "ограниченный режим, плагин не обнаружен",
            ["active_last_event"] = "активен, последнее событие {0} сек. назад",
            ["limited_last_event"] = "ограниченный режим, последнее событие {0}",
            ["no_activity"] = "Активность пока не записана.",
            ["was_opened_at"] = "{0}: начало {1}, конец {2}, всего {3}.",
            ["cleanup_completed"] = "Очистка завершена.",
            ["db_unavailable"] = "База данных недоступна. Приложение не может запуститься.",
            ["db_error_title"] = "Ошибка базы данных",
            ["browse"] = "Обзор",
            ["current_password"] = "Текущий пароль",
            ["new_password"] = "Новый пароль",
            ["confirm_password"] = "Подтверждение",
            ["save"] = "Сохранить",
            ["cancel"] = "Отмена",
            ["exit"] = "Выход",
            ["password_min_length"] = "Пароль должен содержать не менее 5 символов.",
            ["passwords_do_not_match"] = "Пароли не совпадают.",
            ["create_password"] = "Создайте локальный пароль",
            ["password_note"] = "Пароль требуется для открытия интерфейса и закрытия приложения.",
            ["password_label"] = "Пароль",
            ["confirm_password_label"] = "Подтверждение пароля",
            ["open_application"] = "Открыть приложение",
            ["close_app"] = "Закрыть 1984",
            ["invalid_password"] = "Неверный пароль.",
            ["enter_password"] = "Введите пароль",
            ["col_user"] = "Пользователь",
            ["col_process_name"] = "Процесс",
            ["col_window_title"] = "Заголовок",
            ["col_started_at"] = "Запуск",
            ["col_duration"] = "Активно",
            ["col_daily_total"] = "Всего за день",
            ["col_browser"] = "Браузер",
            ["col_domain"] = "Домен",
            ["col_url"] = "URL",
            ["col_captured_at"] = "Время снимка",
            ["install_plugin"] = "Установить плагин браузера",
            ["plugin_install_instructions"] = "Chrome/Edge/Brave/Opera: откройте страницу расширений, включите режим разработчика, Загрузить распакованное → папка 'chromium'.\nFirefox: about:debugging → Загрузить временное дополнение → 'firefox/manifest.json'.",
            ["report_auto_interval"] = "Автоотчёт (мин, 0=выкл)",
        }
    };

    public static string Get(string key, string? locale = null)
    {
        var loc = locale ?? "en";
        if (Strings.TryGetValue(loc, out var dict) && dict.TryGetValue(key, out var value))
        {
            return value;
        }

        if (Strings.TryGetValue("en", out var enDict) && enDict.TryGetValue(key, out var enValue))
        {
            return enValue;
        }

        return key;
    }

    public static string Fmt(string key, string? locale, params object?[] args)
    {
        return string.Format(Get(key, locale), args);
    }
}
